version: "3.7"

services:
  mysql:
    image: mysql:5.7
    container_name: example_mysql
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - 33006:3306
