package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"time"

	"github.com/dgryski/trifles/uuid"
	"github.com/songtomtom/gqlgen-apollo-subscriptions/graph/model"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	post := model.Post{ID: input.ID}
	if err := r.DB.WithContext(ctx).Create(&post).Error; err != nil {
		return nil, fmt.Errorf("create post: %w", err)
	}
	return &post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	comment := model.Comment{
		ID:      uuid.UUIDv4(),
		PostID:  input.PostID,
		Content: input.Content,
	}
	if err := r.DB.WithContext(ctx).Create(&comment).Error; err != nil {
		return nil, fmt.Errorf("create comment: %w", err)
	}

	// DB 에 저장이 끝난 뒤에 발행한다. 저장 전에 발행하면 구독자가 아직 없는 댓글을 먼저 보게 된다.
	// Publish 는 블로킹되지 않으므로 구독자가 느려도 뮤테이션 응답은 지연되지 않는다.
	r.Observer.Publish(input.PostID, &comment)

	return &comment, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, where model.CommentsWhere) ([]*model.Comment, error) {
	var comments []*model.Comment
	if err := r.DB.WithContext(ctx).Where("post_id = ?", where.PostID).Find(&comments).Error; err != nil {
		return nil, fmt.Errorf("list comments: %w", err)
	}
	return comments, nil
}

// CurrentTime is the resolver for the currentTime field.
func (r *subscriptionResolver) CurrentTime(ctx context.Context) (<-chan *model.Time, error) {
	ch := make(chan *model.Time, 1)

	go func() {
		defer close(ch)
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()

		for {
			select {
			case <-ctx.Done():
				// 클라이언트가 구독을 끊으면 gqlgen 이 ctx 를 취소한다. 여기서 고루틴을 끝내야 누수가 없다.
				return
			case now := <-ticker.C:
				select {
				case ch <- &model.Time{UnixTime: int(now.Unix()), TimeStamp: now.Format(time.RFC3339)}:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return ch, nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, input model.AddedCommentInput) (<-chan *model.Comment, error) {
	ch, unsubscribe := r.Observer.Subscribe(input.PostID)

	// 구독이 끝나면(클라이언트 종료, 네트워크 단절, 서버 셧다운) 등록을 지우고 채널을 닫는다.
	// 채널이 닫히면 gqlgen 은 클라이언트에 complete 메시지를 보내고 구독을 정리한다.
	go func() {
		<-ctx.Done()
		unsubscribe()
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
